import { MessageTypes } from './types';

export interface RequestReg {
  type: MessageTypes.reg;
  data: {
    name: string;
    password: string;
  };
  id: 0;
}

export interface ResponseReg {
  type: MessageTypes.reg;
  data: {
    name: string;
    index: number | string;
    error: boolean;
    errorText: string;
  };
  id: 0;
}

export interface Room {
  roomId: number | string;
  roomUsers: {
    name: string;
    index: number | string;
  }[];
}

export interface CreateGame {
  type: MessageTypes.createGame; //send for both players in the room, after they are connected to the room
  data: {
    idGame: number | string;
    idPlayer:
      | number
      | string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
  };
  id: 0;
}
